### ISSUE TITLE
Bias Forecast

### ISSUE THREAD

**Issue by cvelascof** [pySTEPS/pysteps#10]
Hi All
I am not sure about the definition of Bias Score at 
https://github.com/pySTEPS/pysteps/blob/013997fcd3015658e32461b1482d32ed343a8d59/pysteps/verification/detcatscores.py#L92

Bias score (frequency bias) should be equal to B = (H + FA)/ (H + M)
as per http://www.cawcr.gov.au/projects/verification/

Carlos

**Comment by pulkkins** [comment]
This issue has been fixed in commit 5ac6a3d.

**Comment by cvelascof** [comment]
Great. Thanks
