### ISSUE TITLE
Suggestions to improve the optical flow interface

### ISSUE THREAD

**Issue by pulkkins** [pySTEPS/pysteps#101]
I think the optical flow interface in its current form is inconsistent. For Lucas-Kanade, VET and Proesmans, we should either
  a) allow any number n of input fields, or
  b) use two input fields
In case a), some kind of temporal averaging would be applied to produce a single advection field. I would prefer b) to keep the implementation modular. For n>2, computation of time series of advection fields and temporal averaging should be implemented in a separate function or module.

The Lucas-Kanade implementation is a bit odd. It allows any number of input fields, but the classical Lucas-Kanade method is formulated for two inputs. It's not clearly specified in the documentation how it works when n>2. This needs to be improved.

My third improvement proposal is to separate the advection field interpolation from the Lucas-Kanade module. The interpolation can be used to post-process the output of any local optical flow method. This could go to the same module with other post-processing methods, such as the temporal averaging mentioned above.

**Comment by dnerini** [comment]
Thank @pulkkins for the suggestions!

I don't have a strong opinion regarding the interface to the optical flow routines. Option b) is certainly the easiest to implement, if we decide to adopt a strict interface for all methods. 
However, option b) is not going to be possible with DARTS and more generally for any method that needs more than 2 fields to compute the motion field. So the question is whether is truly necessary to have the same number of input fields for all methods?

Concerning the Lucas-Kanade method, I'm going to open a new branch to implement the suggested modifications, in particular concerning the separation of the interpolation routine.

**Comment by aperezhortal** [comment]
Some considerations regarding VET. When 3 fields are given (t1, t2, t3), the motion field obtained is the one that minimized the sum of the cost function for (t1, t2) + (t2, t3). This gives different results than averaging the motion fields obtained  (t1, t2) and (t2, t3).

Using 3 times steps may be helpful for the convergence of the method and gives a better motion field.
But, using 2 fields also gives good results.

**Comment by dnerini** [comment]
Another aspect that could be improved with respect to the optical flow methods interface is the support of masked arrays. Currently it is possible to pass masked arrays (or np.nan) only to the VET and LK methods.

**Comment by pulkkins** [comment]
In addition, the docstring of each method should specify how nan values are treated. Also make sure to throw an exception if the method is not able to handle nan values or masked arrays.

**Comment by dnerini** [comment]
#110 closes this issue.
