### ISSUE TITLE
R_thr argument in SPROG

### ISSUE THREAD

**Issue by dnerini** [pySTEPS/pysteps#108]
There are some inconsistencies with respect to the `R_thr `argument in the `pysteps.nowcasts.sprog.forecast` method:

- the description of the `R_thr` argument mentions a `mask_method` argument which does not exist. 
- `R_thr` is required when `probmatching_method="mean"` ([here](https://github.com/pySTEPS/pysteps/blob/856f5677afd74f6b54f01d17b1e164420a5b9f74/pysteps/nowcasts/sprog.py#L250))
- `R_thr` is always required ([here](https://github.com/pySTEPS/pysteps/blob/856f5677afd74f6b54f01d17b1e164420a5b9f74/pysteps/nowcasts/sprog.py#L254))

@spulkkin , can you have a look at this?

**Comment by pulkkins** [comment]
This has been fixed in commit 4567643.
