### ISSUE TITLE
Proesmans function returns nan for zero precipitation fields

### ISSUE THREAD

**Issue by aperezhortal** [pySTEPS/pysteps#109]
@pulkkins, the proesmans module is returning nan when the input fields haves zero precipitation in the entire domain. Is this an expected behavior? 

Below the snippet to reproduce the problem:
```
import numpy as np

from pysteps import motion

motion_method = motion.get_method('proesmans')

print(motion_method(np.zeros((2, 50, 50))))
```

**Comment by pulkkins** [comment]
This has been fixed in commit b0b0f4e.
