### ISSUE TITLE
Change names of top-level modules

### ISSUE THREAD

**Issue by pulkkins** [pySTEPS/pysteps#11]
Naming of the modules in the top-level pysteps directory is inconsistent. Suggested changes:
- Replace "advection" with "extrapolation", because the submodules in this directory implement extrapolation methods.
- Replace "optflow" with more generic "motion", since this module can contain more general motion-related functionality (such as temporal evolution of the motion field).

**Comment by dnerini** [comment]
I agree that some modules need better names and the two examples cited above make a lot of sense to me.
Can we think of other improvements in this sense?

**Comment by pulkkins** [comment]
For the advection and optflow modules, this issue has been resolved in commits 9dce013 and 1957d0d.

**Comment by dnerini** [comment]
I think this issue was resolved already some time ago and can be closed.
