### ISSUE TITLE
Implement GeoTIFF exporter

### ISSUE THREAD

**Issue by pulkkins** [pySTEPS/pysteps#116]
Some users have expressed their interest to read the pysteps output in GeoTIFF format. This is because GeoTIFF is the standard format for GIS applications (e.g. QGIS). Being able to easily import pysteps output into GIS applications would be especially helpful for visualization purposes.

**Comment by kmuehlbauer** [comment]
@pulkkins You might not want to pull in wradlib as a dependency, but maybe your users (eg. me) already have it installed. Then you might get some inspiration from [this wradlib-notebook](https://docs.wradlib.org/en/stable/notebooks/fileio/wradlib_gis_export_example.html). This uses GDAL as another big dependency (which QGIS users normally also have installed). It can output to all available GDAL raster formats.

**Comment by aperezhortal** [comment]
PR #118 closes this issue.

**Comment by Afshinshafei** [comment]
Does somebody know that, how can I import fmi_geotiff dataset? when I use "fmi" it uses the pgm. but how can use geotiff dataset?
