### ISSUE TITLE
NetCDF exporter broken with netcdf4-python >= 1.5.1

### ISSUE THREAD

**Issue by marack** [pySTEPS/pysteps#120]
The netcdf exporter is throwing an exception when used with recent versions of the netCDF4 python module.  This is due to the following lines (similar for `lat`):

```
lon, lat = pr(x_2d.flatten(), y_2d.flatten(), inverse=True)
...
var_lon[:] = lon
var_lat[:] = lat
```

The `lon` and `lat` variables are flat 1D arrays, but they are being assigned into 2D NetCDF variables.

In earlier versions of netCDF4 this was permissible.  As of version 1.5.1 this behaviour is now illegal and throws an exception.  See https://github.com/Unidata/netcdf4-python/issues/939.

The `lon` and `lat` arrays should be reshaped back to 2D before assignment.

**Comment by marack** [comment]
Note for others, I'm currently working around this by explicitly downgrading the `netcdf4` module to version 1.5.0 (`conda install netcdf=1.5.0`).

**Comment by RubenImhoff** [comment]
I noticed this too yesterday. Downgrading the netCDF4 module is a good quick-and-dirty fix. With netCDF4 < 1.5.1, assigning a 2D array to the netCDF variables works too, right? In that case, I would propose to just fix the code appropriately and thus reshape lat and lon to 2D arrays. This should be a relatively easy fix.

**Comment by cvelascof** [comment]
working on this, and adding a test as well.

**Comment by aperezhortal** [comment]
Hi @marack, PR #122 closes this issue. Feel free to re-open it if you experience any issues.
