### ISSUE TITLE
Calling pySTEPS from Com-SWIRLS/SwirlsPy

### ISSUE THREAD

**Issue by wcwoo** [pySTEPS/pysteps#124]
Hi! We are about to release SwirlsPy 2.0.8, which enables calling pySTEPS' methods from SwirlsPy.  I envisage that it would be useful for comparison of nowcasting schemes and multi-model ensemble.  

I've since drafted an announcement, a part of which as follow:

> Many thanks to the [pySTEPS team](https://pysteps.readthedocs.io/en/latest/) for releasing codes under BSD 3-Clause license, and @slyeung for developing the wrappers and associated methods, it is now possible to call pySTEPS' functions from SwirlsPy.  Two examples have been added to illustrate potential applications.  Detailed changes are documented in the [Change Log](https://docs.com-swirls.org/latest/changelog.html).

The paragraph serves as an acknowledgement of pySTEPS, but then I came to realize that according to the BSD 3-clause:

> 3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

Out of prudence, may I know if my draft announcement is fine with you, @dnerini?

**Comment by dnerini** [comment]
Hi @wcwoo! Thanks for the good news and congratulations on the new release!
The way I see it, this is more an acknowledgment, rather than the promotion/endorsement of a product. Hence, you can keep the announcement as it is, no problem.
Please let us know of any feedback from SwirlsPy users using pysteps methods!

**Comment by wcwoo** [comment]
Thanks a lot!  We've just launched the release.

Apparently we will be the first user to use pySTEPS from SwirlsPy :)  I'll let you know once we put it into operation.
