### ISSUE TITLE
EEC radar data

### ISSUE THREAD

**Issue by abdullahali-radar** [pySTEPS/pysteps#128]
Is it possible to process EEC radar data (netcdf or hdf5 format) ?
We have a lot of weather radar and we need this very nice thing.

**Comment by aperezhortal** [comment]
Hello @abdullahali-radar, the ECC data that you are referring to, are 2D composites or 3D polar scans? 

The optical flow and extrapolation methods in pysteps uses 2D cartesian grids to retrieve the motion vectors and extrapolate the precipitation fields. 

Right now, pysteps does not have importers for ECC format. But, If you have a 2D in netcdf format you can use the netCDF4 to read the files and store the radar fields in a 2D numpy array. Once you have that, you can make use of most pysteps functions. 

On the other hand, if the ECC data are 3D polar volumes, you can construct a 2Dmosaic first with other libraries (maybe wradlib or pyart can be useful for this) and then use pysteps.

**Comment by abdullahali-radar** [comment]
@aperezhortal 
Oh I see now. We are able to extract the 3D polar scan and get the max reflectivity in 2D numpy array with wradlib.
After I get the 2D numpy array, what function that I can use to do the optical flow and extrapolation?

**Comment by dnerini** [comment]
Hi @abdullahali-radar and welcome to pysteps!
In the documention, you will find a gallery of examples that shows how to use the basic methods of the library, including optical flow and extrapolation:
https://pysteps.readthedocs.io/en/latest/auto_examples/index.html

We also have a slack channel where you can ask for more support and discuss your implementation. If you want to join it, just send me your email address, so that I can send you the invitation.

Hope this helps.

**Comment by abdullahali-radar** [comment]
Hi @dnerini,
I will read carefully and try to understand the example. I've already install the pysteps but always fail when try to download the example data.

Yes, that's exactly what I want. Here is my email : [edit: removed address]. Waiting for your invitation!

**Comment by aperezhortal** [comment]
> I've already install the pysteps but always fail when try to download the example data.

@abdullahali-radar, if you are still having issues downloading the example data, feel free to open an issue in the [pysteps-data GitHub issue tracker](https://github.com/pySTEPS/pysteps-data/issues) and we can follow up the problem from there.
