### ISSUE TITLE
Use specific exception types instead of generic Exception

### ISSUE THREAD

**Issue by pulkkins** [pySTEPS/pysteps#13]
Generic Exception classes are used in many places where a more specific exception type would be appropriate. Find ones from the builtin Python exception classes or implement own.

**Comment by aperezhortal** [comment]
Some of the generic exception were replaced by two custom exception: MissingOptionalDependency and DataModelError.

The rest of the generic exception were replaced by build-in Exceptions.

Commits 28d7d7c25d17843df2c18b4213be51e476ee0381 5100b85fd59b89846b7c150964e8d3786c6f080d 5100b85fd59b89846b7c150964e8d3786c6f080d close this issue.
