### ISSUE TITLE
error in _interpolator()

### ISSUE THREAD

**Issue by Yuchaowni** [pySTEPS/pysteps#130]
I think there is an error in the _interpolator() function of models.py:

at line 606:
```
def _interpolator(points, coord_source, coord_target, method="idw"):
    coord_source_i, coord_source_j = coord_source
    coord_target_i, coord_target_j = coord_target
    # reshape
    trg = np.vstack((coord_source_i.ravel(), coord_source_j.ravel())).T
    src = np.vstack((coord_target_i.ravel(), coord_target_j.ravel())).T
```

I think trg and src should exchange their positions.

**Comment by dnerini** [comment]
Hi @Yuchaowni 

Thanks for your bug report! Can you please link the piece of code that you looking at? I'm not aware of any pysteps module named "models.py".

**Comment by Yuchaowni** [comment]
Thank you for your reply. Sorry, it turns out that I had mistaken the source of this code.

**Comment by dnerini** [comment]
https://github.com/hydrogo/rainymotion/blob/master/rainymotion/models.py @hydrogo
;-)

**Comment by hydrogo** [comment]
Solved ;-)
