### ISSUE TITLE
Python>=3.6

### ISSUE THREAD

**Issue by dnerini** [pySTEPS/pysteps#136]
Currently python=3.6 is required when installing pysteps, for example in the environment files:

https://github.com/pySTEPS/pysteps/blob/c326210a4107012250b4975314bd64d41cacf5e4/environment.yml#L6

https://github.com/pySTEPS/pysteps/blob/1307ab810efa303a836c31532d2da2942d148161/environment_dev.yml#L7

but also when running Travis CI and tox:

https://github.com/pySTEPS/pysteps/blob/c326210a4107012250b4975314bd64d41cacf5e4/.travis.yml#L12

https://github.com/pySTEPS/pysteps/blob/1307ab810efa303a836c31532d2da2942d148161/tox.ini#L11

while we use python=3.7 when building the documentation:

https://github.com/pySTEPS/pysteps/blob/1307ab810efa303a836c31532d2da2942d148161/.readthedocs.yml#L13

I propose to set python>=3.6 as requirement for pysteps and therefore test for py36, py37 and py38. 
I'll test this solution and see if it doesn't become too cumbersome when testing the package.

**Comment by dnerini** [comment]
The build fails on macOS for python=3.8 because of an UnsatisfiableError from conda:
https://github.com/pySTEPS/pysteps/runs/449949227

```
UnsatisfiableError: The following specifications were found

to be incompatible with the existing python installation in your environment:

Specifications:

  - attrdict -> python[version='2.7.*|3.4.*|3.5.*|3.6.*']

  - codecov -> python[version='2.7.*|3.5.*|3.6.*']

  - opencv -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']

  - pytest-cov -> python[version='2.7.*|3.4.*|3.5.*|3.6.*|>=2.7,<2.8.0a0|>=3.5,<3.6.0a0|>=3.6,<3.7.0a0|>=3.7,<3.8.0a0']

Your python: python=3.8
```

Need to dig a bit into this. Any help is appreciated.

**Comment by aperezhortal** [comment]
> The build fails on macOS for python=3.8 because of an UnsatisfiableError from conda:
https://github.com/pySTEPS/pysteps/runs/449949227

It seems that for OsX and python3.8, basemap and cartopy are incompatible. 

Removing basemaps from the dependencies solves the conda environment issue.

Since **basemap** is no longer supported, maybe we should consider leaving Cartopy as the only backend in a future release (#8)

**Comment by dnerini** [comment]
Brilliant, thanks a lot @aperezhortal ! 
This effectively solved the failing build on Travis:
https://travis-ci.com/pySTEPS/pysteps/builds/149503295

**Comment by dnerini** [comment]
#138 closes this issue.
