### ISSUE TITLE
Windows installation

### ISSUE THREAD

**Issue by jctw2008** [pySTEPS/pysteps#156]
I tried to place the pystepsrc parameters file in the users folder by following the institution and found that the correct configuration file cannot be loaded by the library. The library’s default rc file was still in the original directory. Is that anything I miss? Many thanks.

P.S. I can see the rc file was copied in the %USERPROFILE%/pysteps/ though.

**Comment by aperezhortal** [comment]
Hi @jctw2008. I checked in a windows installation where pysteps look for the config files and everything seems to be running as expected. 

To check the sequence of configuration paths where pysteps looks you can run the following script:
```
import pysteps as ps

for path in ps._fconfig_candidates_generator():
    print(path)
```
Does any of those paths point to the `pystepsrc` file that you copied following the installation instructions?

Note that  `%USERPROFILE%"`indicates the system variable for your user path.  The actual path may look like: `C:\Users\your_user_name\pysteps\pystepsrc`

**Comment by jctw2008** [comment]
Hi @aperezhortal Thank you for the reply.
I can see one of the paths was pointed to `C:\Users\my_user_name\pysteps\pystepsrc`. So that means everything is running as expected. 

Another question, I followed the code to download the sample data, it showed the `PermissionError: [Errno 13] Permission denied: 'C:\\Users\\jerry\\AppData\\Local\\Temp\\tmpeun1qgfz' `
I can see the `pysteps_data` folder was created but no data in. I guess it was due to this permission error. The manual installation works but I was wondering if the error can be solved? Many thanks.

**Comment by aperezhortal** [comment]
> I can see one of the paths was pointed to C:\Users\my_user_name\pysteps\pystepsrc. So that means everything is running as expected.

To be sure that the correct file is loaded when pysteps is imported, you can run:

```
import pysteps
_=pysteps.load_config_file(verbose=True)
```

>  I followed the code to download the sample data, it showed the PermissionError: [Errno 13] Permission denied: 'C:\\Users\\jerry\\AppData\\Local\\Temp\\tmpeun1qgfz' 

I saw the same error in my windows setup. Thanks for pointing this out. I will take a look at it.

**Comment by jctw2008** [comment]
> To be sure that the correct file is loaded when pysteps is imported, you can run:
> 
> ```
> import pysteps
> _=pysteps.load_config_file(verbose=True)
> ```
I think I figure out the reason why the rc file is not loaded properly, because I run `$ mkdir -p %USERPROFILE%\pysteps` in the **anaconda terminal**, then a new folder `%USERPROFILE%` was created in my home directory. 
I followed the setup up instruction in windows command terminal, it worked and showed `Pysteps configuration file found at: C:\Users\jerry\pysteps\pystepsrc` after running the code `import pysteps`

**Comment by jctw2008** [comment]
one more comment, the code `$ cp C:\path\to\pysteps\library\pystepsrc %USERPROFILE%\pysteps\pystepsrc` should be `$ copy C:\path\to\pysteps\library\pystepsrc %USERPROFILE%\pysteps\pystepsrc` in windows terminal
