### ISSUE TITLE
Padding bug in VET motion code

### ISSUE THREAD

**Issue by fionaRust** [pySTEPS/pysteps#163]
Whilst using the VET motion code we uncovered a bug when using the padding option:

- When using a masked array as input the padding isn't added to the array, but it is still removed before returning the calculated velocity fields, resulting in velocity fields the is smaller in the x and y dimensions than the input arrays.
- When using an array without a mask the padding is added and removed correctly. 

I think the problem is with the if statement here: https://github.com/pySTEPS/pysteps/blob/master/pysteps/motion/vet.py#L517

**Comment by aperezhortal** [comment]
Hi @fionaRust, welcome to PySteps! 

Indeed the portion of code that you pointed out is causing the issue since the padding is not been handled correctly. Thanks for finding the issue! I will fix it shortly.

**Comment by aperezhortal** [comment]
PR #164 should close this issue. @fionaRust feel free to re-open it if you experience any problems.
