### ISSUE TITLE
Incorrect plot_geography call when plotting motion field over map

### ISSUE THREAD

**Issue by miaoneng** [pySTEPS/pysteps#165]
The plotting function in `pysteps.visualization.precipfields` and `pysteps.visualization.motionfields` are very different, and the one in `motionfields.py` doesn't match documented API. 

`motionfields.py:136` requests key `xpixelsize` and key `ypixelsize` from `geodata` but not documented, and implementation on `precipfields` is different (not using it). Later when it calls `plot_geography`, it puts 9 positional args. but `plot_geography` only accepts 6.

Overall, it looks like plotting in motionfields is broken.

**Comment by dnerini** [comment]
Hello @striges, welcome to pysteps and thanks for reporting this issue with the visualization methods.
I'll gladly have a look into it.

**Comment by dnerini** [comment]
PR #166 should close this issue. @striges feel free to re-open it if you experience any problems.
