### ISSUE TITLE
Allow more flexible output time steps

### ISSUE THREAD

**Issue by pulkkins** [pySTEPS/pysteps#176]
Currently the nowcast methods implemented in pysteps produce outputs having the same time step with the inputs. Several users have expressed their interest to relax this requirement. This would be needed for computing nowcasts of accumulated rainfall. For instance, if the time interval between the inputs is 5-15 minutes, the output time step is too coarse for computing accurate hourly accumulations.

Basically the above would require a modification of the nowcast interface to allow user-supplied output time steps. This could be implemented by adding an optional keyword argument. The extrapolation interface already supports arbitrary time steps, so the above can be trivially done for the extrapolation-only nowcast. For S-PROG, STEPS and ANVIL, one would also need to modify the autoregressive model (also discussed in Issue #115). The easiest (but not optimal) approach would be to apply linear time-weighted interpolation to the outputs of the AR model.

**Comment by dnerini** [comment]
#191 was merged, can we close this? @pulkkins
