### ISSUE TITLE
Improve the semi-Lagrangian extrapolation

### ISSUE THREAD

**Issue by pulkkins** [pySTEPS/pysteps#182]
A closer investigation is needed to verify that the semi-Lagrangian extrapolation (pysteps.extrapolation.semilagrangian) is working correctly. It appears to produce visible artefacts in some cases. See the example below, which shows six-step extrapolation applied to a smooth precipitation field obtained by convolution. 

Similar artefacts appear with all optical flow methods, so I believe the problem is in the extrapolation. I'm suspecting that the culprit is the spline interpolation (currently implemented by using scipy.ndimage.map_coordinates). Another issue is that handling of nan values is not currently well-defined. This depends on the internal details of map_coordinates, which are not specified in the scipy documentation.
![nowcast_artefacts](https://user-images.githubusercontent.com/17096036/99272343-5dab9800-2830-11eb-9d9b-2a1615429b94.png)

To fix the above issues, I will try to implement simple bilinear interpolation with capability to handle nan values. In my opinion, this is how it should have been implemented in the first place. Spline interpolation, that is known to be less robust, should be an optional feature.

**Comment by dnerini** [comment]
Interesting, thanks for pointing this out, @pulkkins !
Could it be related to the order of the spline interpolation? Currently we use `order=0` in `ndimage.map_coordinates`.

**Comment by pulkkins** [comment]
The choice for order=0 was made for a good reason. If the inputs contain nan values (i.e. those outside the radar mask), choosing order=1 or order=2 yields large regions of nan values in the output. I guess this is because high-order interpolation needs a large number of neighbors.

**Comment by pulkkins** [comment]
It turned out that `order=0` gives nearest interpolation. This is not what we want and probably explains those artefacts. Therefore I made a commit to use `order=1` (linear interpolation). It computes interpolated values from four nearest pixels by omitting nans. Cubic interpolation (`order=3`) with `prefilter=True` would probably be the best option but I haven't figured out how to make it handle nan values.

**Comment by dnerini** [comment]
Very nice that you found a plausible cause. It would be interesting to see whether using linear interpolation instead of nearest interpolation affects the performance of the advection routine, especially in case of large domains. 

Would it be possible to compare the two settings in terms of memory and computing time?

**Comment by pulkkins** [comment]
I'll do that and create a separate branch for testing. I also changed the default order back to 0 in the master. More testing is needed.
