### ISSUE TITLE
Implement linear blending

### ISSUE THREAD

**Issue by ladc** [pySTEPS/pysteps#226]
Implement a linear blending algorithm which can be applied on the different nowcast algorithms.

**Comment by ladc** [comment]
Hi everyone, a linear blending algorithm has been implemented. I think it will be useful in its own right as well as serve as a benchmark for the more advanced blending techniques. @wdewettin will do a pull request. I propose to do this PR against the current pysteps-v2 branch. In principle it could also be integrated in master since it extends the current methods and does not break any interfaces. But since blending would be a major part of pysteps-v2 I would propose to add it there.

**Comment by RubenImhoff** [comment]
Sounds good, @ladc! I agree to add it to the v2 branch. I can have a look at @wdewettin's PR once it's there.
