### ISSUE TITLE
More efficient FFT computation

### ISSUE THREAD

**Issue by pulkkins** [pySTEPS/pysteps#23]
The current implementation of the cascade decomposition uses fft2 and ifft2. These implement the generic Fourier transform that can take complex-valued inputs. For real-valued inputs, which is always the case in pysteps, we should use the optimized rfft2 and irfft2 with roughly half of the computational cost and memory usage.

**Comment by pulkkins** [comment]
I have currently implemented the above for the cascade decomposition (including computation of the bandpass filter weights) and the nonparametric noise generator. This still needs to be implemented for the parametric, nested and ssft noise generators.

**Comment by dnerini** [comment]
> AttributeError: module 'scipy.fftpack' has no attribute 'rfft2'

@pulkkins , I get this error when it tries to call rfft2 through scipy.fftpack. Don't you get the same error?

**Comment by pulkkins** [comment]
It turned out that scipy.fftpack does not implement rfft2/irfft2. In those cases we have to revert back to numpy.fft. I'll take this into account when I implement the FFT module (see issue #28).

**Comment by pulkkins** [comment]
I also got that because scipy.fftpack does not implement rfft2. I'm working
on a solution to this problem.

**Comment by dnerini** [comment]
Ok thanks for the explanation. I will work on implementing rfft2 for the remaining fftgenerators. From what I could see, this seems to provide a significant improvement in performance, well done!

**Comment by dnerini** [comment]
This has been implemented some time ago.
