### ISSUE TITLE
Blending with NWP data

### ISSUE THREAD

**Issue by RubenImhoff** [pySTEPS/pysteps#24]
Hi all,

With version 0.2 coming up, I was wondering whether there are any plans to implement a functionality for blending with NWP data in next releases? 

Thanks!

**Comment by dnerini** [comment]
Hi @RubenImhoff and welcome to pysteps!

I'm afraid we won't be able to include blending with NWP in the incoming 0.2 release. 

The way I see it, this will require quite an effort, not only for the blending itself, but also to provide the routines to import various NWP formats and regrid them to the same radar grid. Also, different NWP require different blending strategies (deterministic vs ensemble, low-resolution vs high-resolution NWP, blending probabilities vs blending actual rain rates). 

In brief, blending will represent a whole new chapter for pysteps and personally I would rather focus at the moment at improving the radar-based (ensemble) nowcasting part and only when this is mature enough then start to work on the blending part.

Of course, anyone would be more than welcomed if he/she wants to start implementing blending routines in pysetps right now.

This said, we do have some experience with blending, so if you urgently need blending for your work, we can try to support you.

**Comment by RubenImhoff** [comment]
Hi Daniele,

Thanks for your complete answer. 

That is already what I thought, unfortunately! Though, focussing on the nowcasting part first, makes sense. 

For my research, I might need to make use of blending in the near future. Perhaps it's good to stay in touch, let's see what we can make of it in pySTEPS. 


Thanks,

Ruben

**Comment by dnerini** [comment]
We are considering adding blending with NWP to pysteps early next year. In the meantime, I'll close this issue, but we'll keep you update on related developments.
