### ISSUE TITLE
No module named 'pysteps.motion._proesmans'

### ISSUE THREAD

**Issue by relmonta** [pySTEPS/pysteps#268]
I installed pysteps on linux machine, using conda and pip, and with both installations when I try to import the packge, I get the same error: 
`ModuleNotFoundError: No module named 'pysteps.motion._proesmans'`

**Comment by dnerini** [comment]
Hi @relmonta, welcome to pysteps!

Can you provide more details on your setup please? What python version are using? Are you installing from source within a conda environment or from PYPI?

**Comment by relmonta** [comment]
Hi @dnerini , Thank you for your reply, 
I am installing it in a new environment from conda-forge following [this guide](https://pysteps.readthedocs.io/en/stable/user_guide/install_pysteps.html#anaconda-install-recommended), my python version is 3.9.7

**Comment by aperezhortal** [comment]
Hi @relmonta ,

Are you executing the `import pysteps...` from a directory containing a clone of the pysteps repository or containing a folder named `pysteps`?  That could cause that kind of import error.

**Comment by dnerini** [comment]
Exactly, could you check that you're not running in the same issue described in #40?

**Comment by relmonta** [comment]
Thank you, that's true.

**Comment by dnerini** [comment]
Very good. I'm not sure how often this issue happens in reality, but I think we'll consider adding a specific note in the documentation ... 

Happy nowcasting!
