### ISSUE TITLE
Make code pep8 compilant

### ISSUE THREAD

**Issue by aperezhortal** [pySTEPS/pysteps#27]
Many parts of the source code do not follow good coding practices recommended for python ([pep8 style guide](https://www.python.org/dev/peps/pep-0008/)).

Although this requires some effort, it will increase the readability of the package library.
A good summary of the standard can be found [here](https://development.robinwinslow.uk/2014/01/05/summary-of-python-code-style-conventions/).

Some good candidates to tackle first are:

**Whitespace and newlines, Indentation, line-length & code wrapping** 

* Always use 4 spaces for indentation (don’t use tabs)
* Write UTF-8
* Max line-length: 79 characters
* Always indent wrapped code for readability
* 2 blank lines before top-level function and class definitions
* 1 blank line before class method definitions
* Use blank lines in functions sparingly
* Avoid extraneous whitespace
* Don’t use whitespace to line up assignment operators (=, :)
* Spaces around = for assignment
* No spaces around = for default parameter values
* Spaces around mathematical operators, but group them sensibly
* Multiple statements on the same line are discouraged

Useful tools
=========

* IDEs : Many development environments show warnings in non-compilant code (like pyCharm). 
* [pylint](https://www.pylint.org/) : code analysis tool. 
* [pep8](https://pep8.readthedocs.io/en/release-1.7.x/) code analysis tool. 
* [autopep8](https://pypi.org/project/autopep8/) : automatically formats Python code to conform to the PEP 8 style guide.

**Comment by dnerini** [comment]
has anyone used [black](https://black.readthedocs.io/) before?

It looks pretty good.
Here it's all it took to reformat the `pysteps/verification/detcontscores.py` module:
```
$>pip install black 
$>black pysteps/verification/detcontscores.py
reformatted pysteps/verification/detcontscores.py
All done! ✨ 🍰 ✨
1 file reformatted.
```
You can see the result in commit 4850ad00baa75c997d92dcccc6cf73b18efede66.

Definitely something to consider for all of us!

Edit: [here](https://news.ycombinator.com/item?id=17151813) you find an interesting discussion about black and its formatting choices.

**Comment by RubenImhoff** [comment]
I think I have missed this post, but definitely worth considering! 
Black seems to work well. Good suggestion, Daniele.

**Comment by aperezhortal** [comment]
The refactoring of the build system (PR #102) includes a configuration for black in the [pyproject.toml](https://github.com/pySTEPS/pysteps/blob/refactor_build_system/pyproject.toml) file.

When black is run in any pysteps sub-directory, it looks upwards until it finds the file and use the default configuration ([more info here](https://black.readthedocs.io/en/stable/pyproject_toml.html#where-black-looks-for-the-file)). In that way, we have a project-wide for black. 

I have been trying black for a while and it is great. I saw that is being used in many projects for quality checks.

**Comment by dnerini** [comment]
I would say that including the black configuration in PR #102 and the new [Code style](https://pysteps.readthedocs.io/en/latest/developer_guide/contributors_guidelines.html#code-style) section in the documentation close this issue.

The repository in still not fully PEP8 compliant, but we have now a good ground to improve on that.

**Comment by aperezhortal** [comment]
What about if we leave it open until we reach a good PEP8 compliance coverage? We are at pretty a pretty low value right now.

**Comment by dnerini** [comment]
#155 closes this
