### ISSUE TITLE
Plotting arguments

### ISSUE THREAD

**Issue by meteoswiss-mdr** [pySTEPS/pysteps#3]
The plotting routines in pySTEPS are amazing, but it would be cool if one could pass further **kw plotting arguments (e.g. when I calculated the UV-differences between DARTS and LucasKanade, I coloured the vectors in red).

https://github.com/pySTEPS/pysteps/blob/c12287fd32b4e1d0af9daa0e83f34f325efa82bc/pysteps/visualization/motionfields.py#L8

**Comment by dnerini** [comment]
Good idea. Changes included in commit 55655313136ddf38fc0e97481c481cb8b2cbe6d6.
