### ISSUE TITLE
Segfaults when using pyfftw

### ISSUE THREAD

**Issue by pulkkins** [pySTEPS/pysteps#30]
Parallel computation of STEPS ensembles occasionally crashes when using pyfftw. The following errors appear in the system log:

[1708862.459601] python[32200]: segfault at 0 ip 00007fa7e771e5b0 sp 00007fa7c9f30598 error 4 in pyfftw.cpython-37m-x86_64-linux-gnu.so[7fa7e7314000+4f1000]

This occurs in Anaconda environment with Python 3.7.1 and pyfftw 0.11.1 when n_ens_members>1 and num_workers>1.

**Comment by pulkkins** [comment]
After more extensive testing, it also turned out that pyfftw occasionally produced incorrect results when executed in parallel. An attempt to fix this was made in commit 4fa3c64. Now each parallel computation of the FFT is done by using a separate pyfftw object, which should prevent multiple threads from accessing the same object. More testing is needed to see if the issue still persists. I'll leave it open for now.

**Comment by galilley** [comment]
Python 2.7.16 and PyFFTW 0.12.0. It seems I observe similar behavior when use pyfftw with pyofss together - wrong values (nan) though all array and segfault from time to time. Could you recomend how I cam obtain more info for debugging?

p.s. yes, I know that py2 is not supported but I can't make the test with py3 right now.

p.p.s. I'm sorry if this message  to the wrong thread as I use pyfftw natively and do not use pysteps project at all...

**Comment by dnerini** [comment]
Hello @galilley, I suggest to ask directly the [pyfftw](https://github.com/pyFFTW/pyFFTW) project. Good luck with your issue!
