### ISSUE TITLE
Minor bug/ disagreement in lagrangian_probability

### ISSUE THREAD

**Issue by aitaten** [pySTEPS/pysteps#307]
The parameter **slope** in _forecast_ function has to be float but parameter **size** in __get_kernel_ function has to be integer. 

Size (actually called scale) is obtained in line 90 with:

`scale = timestep * slope`

Consequently, if slope is actually a float (in the existing test is always an integer), the _get_kernel function returns an error and the _forecast_ function fails without returning the forecast.

**Comment by dnerini** [comment]
Close by #308.
