### ISSUE TITLE
Unable to run any of the example scripts

### ISSUE THREAD

**Issue by winash12** [pySTEPS/pysteps#313]
Installed the latest version of pysteps and I am wanting to run the example scripts that come with the product. But no sample data has been provided. Any suggestions on where I can get access to sample data ? 

Specifically I am interested in the data and the script that generates this plot - 
![image](https://user-images.githubusercontent.com/9129700/198501348-fbe8cad6-3b70-4a92-afba-d6a217ef5583.png)

**Comment by dnerini** [comment]
Hi @winash12 , have you already looked at the this page in the documentation?

https://pysteps.readthedocs.io/en/stable/user_guide/example_data.html#example-data

This should provide you with all the information you need.

**Comment by winash12** [comment]
@dnerini Thanks for the quick response. Will install and try what is mentioned in the docs.

**Comment by dnerini** [comment]
> Specifically I am interested in the data and the script that generates this plot 

The data used for that plot are from the example dataset of FMI (see the page linked above), while the script is the same used here: https://pysteps.readthedocs.io/en/stable/auto_examples/plot_steps_nowcast.html#sphx-glr-auto-examples-plot-steps-nowcast-py

**Comment by winash12** [comment]
@dnerini Under your tutelage managed to run most of the scripts successfully ! Few scripts gave some errors I will open those separately if necessary.

My real world use case would be using netCDF radar files or HDF5 radar files.
