### ISSUE TITLE
how to import my own dataset (.tiff)

### ISSUE THREAD

**Issue by Afshinshafei** [pySTEPS/pysteps#315]
First of all thank you for the great work.
I have a very simple or maybe silly question and issue with code. I want to have a nowcasting with geotiff dataset of my own, but I cant import my dataset into the model. how can I use my custom dataset (.tiff)?
I am using google colab, and modified a custom config file, which shows the dataset path and etc. as below, in the fmi_geotiff part:

{
    "silent_import": false,
    "outputs": {
        "path_outputs": "./"
    },
    "plot": {
        "motion_plot": "quiver",
        "colorscale": "pysteps"
    },
    "data_sources": {
        "bom": {
            "root_path": "/content/pysteps_data/radar/bom",
            "path_fmt": "prcp-cscn/2/%Y/%m/%d",
            "fn_pattern": "2_%Y%m%d_%H%M00.prcp-cscn",
            "fn_ext": "nc",
            "importer": "bom_rf3",
            "timestep": 6,
            "importer_kwargs": {
                "gzipped": true
            }
        },
        "fmi": {
            "root_path": "/content/pysteps_data/radar/fmi/pgm",
            "path_fmt": "%Y%m%d",
            "fn_pattern": "%Y%m%d%H%M_fmi.radar.composite.lowest_FIN_SUOMI1",
            "fn_ext": "pgm.gz",
            "importer": "fmi_pgm",
            "timestep": 5,
            "importer_kwargs": {
                "gzipped": true
            }
        },
        "fmi_geotiff": {
            "root_path": "/content/drive/Shareddrives/Me/pysteps/data/2020_11",
            "path_fmt": "%d/SRI/SRI_vpr/geotiff",
            "fn_pattern": "SRI_vpr_%d-%m-%Y_%H-%M",
            "fn_ext": "tiff",
            "importer": "fmi_geotiff",
            "timestep": 5,
            "importer_kwargs": {}
        },
        "mch": {
            "root_path": "/content/pysteps_data/radar/mch",
            "path_fmt": "%Y%m%d",
            "fn_pattern": "AQC%y%j%H%M?_00005.801",
            "fn_ext": "gif",
            "importer": "mch_gif",
            "timestep": 5,
            "importer_kwargs": {
                "product": "AQC",
                "unit": "mm",
                "accutime": 5
            }
        },
        "mrms": {
            "root_path": "/content/pysteps_data/mrms",
            "path_fmt": "%Y/%m/%d",
            "fn_pattern": "PrecipRate_00.00_%Y%m%d-%H%M%S",
            "fn_ext": "grib2",
            "importer": "mrms_grib",
            "timestep": 2,
            "importer_kwargs": {}
        },
        "opera": {
            "root_path": "/content/pysteps_data/radar/OPERA",
            "path_fmt": "%Y%m%d",
            "fn_pattern": "T_PAAH21_C_EUOC_%Y%m%d%H%M%S",
            "fn_ext": "hdf",
            "importer": "opera_hdf5",
            "timestep": 15,
            "importer_kwargs": {}
        },
        "knmi": {
            "root_path": "/content/pysteps_data/radar/KNMI",
            "path_fmt": "%Y/%m",
            "fn_pattern": "RAD_NL25_RAP_5min_%Y%m%d%H%M",
            "fn_ext": "h5",
            "importer": "knmi_hdf5",
            "timestep": 5,
            "importer_kwargs": {
                "accutime": 5,
                "qty": "ACRR",
                "pixelsize": 1000.0
            }
        },
        "rmi": {
            "root_path": "/content/pysteps_data/radar/rmi/radqpe",
            "path_fmt": "%Y%m%d",
            "fn_pattern": "%Y%m%d%H%M00.rad.best.comp.rate.qpe",
            "fn_ext": "hdf",
            "importer": "odim_hdf5",
            "timestep": 5,
            "importer_kwargs": {
                "accutime": 5.0
            }
        },
        "saf": {
            "root_path": "/content/pysteps_data/saf",
            "path_fmt": "%Y%m%d/CRR",
            "fn_pattern": "S_NWC_CRR_MSG4_Europe-VISIR_%Y%m%dT%H%M00Z",
            "fn_ext": "nc",
            "importer": "saf_crri",
            "timestep": 15,
            "importer_kwargs": {
                "gzipped": true
            }
        },
        "bom_nwp": {
            "root_path": "/content/pysteps_data/nwp/bom",
            "path_fmt": "%Y/%m/%d",
            "fn_pattern": "%Y%m%d_%H00_regrid_short",
            "fn_ext": "nc",
            "importer": "bom_nwp",
            "timestep": 10,
            "importer_kwargs": {
                "gzipped": true
            }
        },
        "rmi_nwp": {
            "root_path": "/content/pysteps_data/nwp/rmi",
            "path_fmt": "%Y/%m/%d",
            "fn_pattern": "ao13_%Y%m%d%H_native_5min",
            "fn_ext": "nc",
            "importer": "rmi_nwp",
            "timestep": 5,
            "importer_kwargs": {
                "gzipped": true
            }
        },
        "knmi_nwp": {
            "root_path": "/content/pysteps_data/nwp/knmi",
            "path_fmt": "%Y/%m/%d",
            "fn_pattern": "%Y%m%d_%H00_Pforecast_Harmonie",
            "fn_ext": "nc",
            "importer": "knmi_nwp",
            "timestep": 60,
            "importer_kwargs": {
                "gzipped": true
            }
        }
    }
}

do I need to create my own importer for geotiff files? or is there any tutorial or a document I can use as a guide?
Thank you very much for your time.

**Comment by dnerini** [comment]
Hi @Afshinshafei, yes, you need to implement your own importer. You can do it "outside" of pysteps and then make sure to format the data in the right way for the pysteps routines (which mostly means creating in a numpy array with all data and a dictionary containing [some metadata](https://pysteps.readthedocs.io/en/stable/pysteps_reference/io.html#pysteps-io-importers)), or you can write a [pysteps plugin](https://pysteps.readthedocs.io/en/stable/developer_guide/importer_plugins.html) that will seamlessly integrate with the package. 

For your case, since you're dealing with geotiff, you might find the [import_fmi_geotiff](https://github.com/pySTEPS/pysteps/blob/8ece5be5e9c8828f5995671d8db3aa97fe0d0546/pysteps/io/importers.py#L552) importer useful to use as an example.

Unfortunately we don't have a dedicated tutorial on the topic, although it would certainly be a good idea to add one. You'd be most welcome to do it through a [pull request](https://pysteps.readthedocs.io/en/stable/developer_guide/contributors_guidelines.html) if you're interested!

**Comment by dnerini** [comment]
I'm closing this if there are no further comments or questions by @Afshinshafei. Feel free to reopen it if needed.
