### ISSUE TITLE
missing module

### ISSUE THREAD

**Issue by DoiManh** [pySTEPS/pysteps#338]
Dear author,
When I run the code for example, there is error like: No module named 'pysteps.motion._proesmans'. Could you provide or update the module "_proesmans" in python format. There is only "_proesmans" in cython format that does not compile with current platform.
Thanks!

**Comment by dnerini** [comment]
Hi @DoiManh 
this looks like a duplicate of #268 and #40. Could you check these two issues first? If you pip installing the pysteps source code, you should make sure that you're not running the python interpreter inside the pysteps root directory, see also the relative waring in the [installation guide](https://pysteps.readthedocs.io/en/stable/user_guide/install_pysteps.html#installation-using-pip).

**Comment by DoiManh** [comment]
thank @dnerini for reply. I have fixed my problem. I installed pysteps on Windows, so there is a difference with other environment.

**Comment by dnerini** [comment]
Very good, glad it worked in the end. Please let us know if we can improve the documentation for our windows users.
