### ISSUE TITLE
Satellite data as input for pysteps

### ISSUE THREAD

**Issue by DoiManh** [pySTEPS/pysteps#339]
Dear authors, 

I am trying to use Pysteps for nowcasting. I got problems with using satellite data (obtained from https://disc.gsfc.nasa.gov/datasets/GPM_3IMERGHHL_06/summary). I try to set up "importers" but it did not work. Could you provide examples or guidelines in the case of satellite data.

Thank you very much for spending your valuable time.

**Comment by PaulaPerezL** [comment]
Can be used pysteps for extrapolating satellite channel images?

**Comment by dnerini** [comment]
Hi @DoiManh apologies for the slow response. You can have a look at our documentation page on importers plugins https://pysteps.readthedocs.io/en/stable/developer_guide/importer_plugins.html

@PaulaPerezL yes satellite data can be used in pysteps, but you need to import them in a suitable format, see above.

**Comment by dnerini** [comment]
closing this issue for now
