### ISSUE TITLE
Can pysteps be applied to prediction of non-radar rainfall data? for example imerg?

### ISSUE THREAD

**Issue by sunmoumou1** [pySTEPS/pysteps#359]
I have recently been working on a project that involves using Imerg data to complete rainfall forecasts. 

Specifically, I now have a variable, sample, which is a ndarray with a shape of (98*98*11). How can I write code that uses 96*96*8 of the first 8 frames to predict 96*96*3 of the next 3 frames? 

Thanks for answering my question. I've looked at the tutorials, but found that they all use radar data, and wonder if the pysteps library can be extended to the situation I'm talking about

**Comment by aperezhortal** [comment]
Hello @sunmoumou1 

Thank you for using PySteps! 

PySteps can work with any type of precipitation measurement (radar, satellite, or model) as long as you map the data to a  Cartesian Grid. This is required for the optical flow methods to work correctly. 

After you have the precipitation data in that grid, you can use PySteps to run the forecasts.

Let us know if you have any other questions.

**Comment by aperezhortal** [comment]
Hello @sunmoumou1 , 

Did the previous answer help? Can we close the issue?

Thanks!

**Comment by dnerini** [comment]
closing this for now, see also #339.
