### ISSUE TITLE
Some problems about 'Verification'

### ISSUE THREAD

**Issue by HY-10** [pySTEPS/pysteps#366]
Can all models (e.g., sprog, anvil, linda, etc.) be run for comparison using the following metrics code (ROC, reliability diagram, FSS, etc.)? I have the following problems when running, and I hope to get your help.

![image](https://github.com/pySTEPS/pysteps/assets/154584217/2bbddde2-7bc6-4f8f-ae4c-6bb239426732)
![image](https://github.com/pySTEPS/pysteps/assets/154584217/e9390982-25ee-4503-8b5b-ecb03611149a)
![image](https://github.com/pySTEPS/pysteps/assets/154584217/a17475f9-4cd0-41bc-8d99-8c7b9e4476db)
![image](https://github.com/pySTEPS/pysteps/assets/154584217/f934bb50-6ace-4364-b10a-7e4e149b6b1c)

**Comment by dnerini** [comment]
dear @HY-10, ROC curves, rank histograms, and reliability diagrams are suitable for ensemble forecasts (e.g. steps, linda), while the FSS is typically used for deterministic forecasts (e.g. sprog, anvil). I hope this helps, feel free to reopen this issue if you have more questions.
