### ISSUE TITLE
missing geographical axis in the plot_precip_field function

### ISSUE THREAD

**Issue by AVI68** [pySTEPS/pysteps#371]

**Comment by dnerini** [comment]
dear @AVI68 did you manage to find a solution to your issue?

**Comment by AVI68** [comment]
Dear dnerini,

Yes, I  found that pysteps automatically prompts a warning for cartopy installation for basemap (if system doesn't have cartopy).  After installing cartopy it is unable to access the metadata for the xaxis and yaxis. so I uninstalled cartopy and used contexily for the basemap. Thank you. 

Regards,
Avijit
