### ISSUE TITLE
Create smooth transition between cells within and outside the radar domain during blending

### ISSUE THREAD

**Issue by ladc** [pySTEPS/pysteps#377]

**Comment by ladc** [comment]
A challenge is to distinguish between the radar mask due to the horizon of the radar vs. the nodata pixels due to clutter, RLAN, etc. These should not be eroded/dilated in the same way. Can we distinguish through metadata/ quality flags? Check with Edouard.

**Comment by sidekock** [comment]
Question: Where in 8.7 should this be added? Before the  # 8.7.2. Apply the masking and prob. matching or just after?

**Comment by sidekock** [comment]
> Before

@RubenImhoff  let me know it should be done before 8.7.2 as this is a post processing step

**Comment by ladc** [comment]
Note that rainfall near the edge of the radar domain is underestimated by the radar.  As the single radar annual mean shows below, even the EDK-based bias-corrected QPE still has this issue 
![qpeverif](https://github.com/user-attachments/assets/ee37c122-256e-49ac-b20e-34bf7711a97c)
source: https://radli.meteo.be/research/rainfall-estimation
In other words, this smoothing is not just cosmetic, it actually makes physical sense to trust the NWP more near the edge of the radar mask.

**Comment by ladc** [comment]
Even better would be a static or dynamic skill map of the QPE which would determine the spatial smoothing weights. As mentioned by @mats-knmi, there's already the possibility to add a quality flag field to the QPE. This could be used to determine the weight of QPE (extrapolation) vs the NWP (if it's a value between 0 and 1). KNMI for example does this.
