### ISSUE TITLE
Fix output format of pysteps (projection info etc.)

### ISSUE THREAD

**Issue by ladc** [pySTEPS/pysteps#378]
See analysis by Felix E (e-mail)

The conventions for projection data are not followed (see https://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#_lambert_conformal)

**Comment by FelixE91** [comment]
The current pysteps output ('blended_nowcast_%Y%m%d.nc') has a projection as global attribute. We should create a crs or projection variable and assign a grid description to each other variable.
For example, variables related to x, y use the Belgian Lambert 2008 projection, and lat, lon coordinates use the standard EPSG4326/WGS84 projection.
