### ISSUE TITLE
Optimizing the number of cascade levels

### ISSUE THREAD

**Issue by sidekock** [pySTEPS/pysteps#386]
[RMI / KNMI / site specific]: scientifically well-founded optimization of the number of cascade levels needed; continuation of Simon's work of last year.

For Belguim this is 6

**Comment by sidekock** [comment]
A visual comparison to check what number of cascade levels is optimal over Belgium. 6 levels looks optimal

[Presentation.pdf](https://github.com/user-attachments/files/16281272/Presentation.pdf)

**Comment by dnerini** [comment]
~~as said, I would welcome a PR that changes the default number of cascade levels (thus reopening the issue if that's ok)~~

I see now #385, sorry
