### ISSUE TITLE
Drop the requirement for square-shaped inputs

### ISSUE THREAD

**Issue by pulkkins** [pySTEPS/pysteps#4]
Currently DARTS and STEPS require the inputs to have a square shape. However, the FFT can be computed from inputs of any shape, and therefore this requirement could be relaxed. This would require implementing more general versions of the bandpass filters and noise generators.

**Comment by dnerini** [comment]
This is almost complete, only the nested generator still requires square domains.

**Comment by dnerini** [comment]
Commit c930fbe5b33ef862b72308602765dad55650c743 closes this issue.
