### ISSUE TITLE
Request for Code Snippet to Recreate Figure 4 from 2023 Paper

### ISSUE THREAD

**Issue by rutkovskii** [pySTEPS/pysteps#415]
Hello,

I found the pySTEPS visualization functions very useful, but I need your help with something.

I read the recent [paper](https://doi.org/10.1002/qj.4461), titled "Scale-dependent blending of ensemble rainfall nowcasts and NWP in the open-source pysteps library" from 2023, which is referenced at the bottom of the README.md. I'm particularly interested in how you created Figure 4.

I don't need the data you used, but I would like to know the code snippet that generated the plots in a horizontal layout and unified all the predictions using the same colorbar.

I would like to use pySTEPS's visualization functionality for my thesis on Precipitation Nowcasting, where I compare DGMR, NowcastNet, and pySTEPS.

Thank you a lot in advance!

**Comment by dnerini** [comment]
Hello @rutkovskii , many thanks for the kind message. I suppose @RubenImhoff should be able to help you out on this one.

**Comment by rutkovskii** [comment]
@dnerini Of course! You are doing very useful project.
@RubenImhoff I will be waiting for your message. Thank you.

**Comment by RubenImhoff** [comment]
Hi @rutkovskii,
Thanks for reaching out and I'm happy to hear that you are working with pysteps! Could you send me your email address, then I will forward you a download link for the Python script that I've used to create figure 4 in the paper.

**Comment by rutkovskii** [comment]
@RubenImhoff 

Hi! Thank you so much.
Email: 
Have a great week ahead!

**Comment by RubenImhoff** [comment]
Great! It should be in your email now. :)

**Comment by dnerini** [comment]
Thanks @RubenImhoff ! I'm closing this, @rutkovskii feel free to reopen if need be (note that I also edited out your email address above)

**Comment by rutkovskii** [comment]
Thank you a lot! Wishing you all the best in your research!
