### ISSUE TITLE
Issue with intensity jump when resampling distributions

### ISSUE THREAD

**Issue by dnerini** [pySTEPS/pysteps#416]
The main issues for me is indeed the intensity jump. Could this be because the NWP has very high intensities, but as these are not present in the blended forecast, the latter is unrealistically scaled up *overall*? 
Do you suggest not filling *anything* outside the radar mask (so we have nans in the final forecast)? Or just for the resampling?

_Originally posted by @ladc in https://github.com/pySTEPS/pysteps/issues/390#issuecomment-2247776140_

**Comment by dnerini** [comment]
I'm opening a new issue here to better track the problem described by @ladc in #390. 

@RubenImhoff did I understand correctly that you're working on it?

**Comment by RubenImhoff** [comment]
Great, thanks, @dnerini! I'm not actively working on it, but happy to make some code changes. I think I prefer to have data outside the radar mask, but not filling anything outside the radar mask for resampling seems the way to go. What do you think?

**Comment by ladc** [comment]
Should be fixed in #428.
