### ISSUE TITLE
pysteps has no module named io

### ISSUE THREAD

**Issue by itsmohitanand** [pySTEPS/pysteps#42]
I am new to pysteps and installed it using conda environment. I am trying to run one of the example scripts. 
```

import matplotlib.pylab as plt
import numpy as np
import pysteps as stp

#Get the two last observations

#read two consecutive radar fields 
filenames = ("sample_mch_radar_composite_00.gif","sample_mch_radar_composite_01.gif")
R = []
for fn in filenames:
    R_, _, metadata = stp.io.import_mch_gif(fn)
    R.append(R_)
    R_ = None
R = np.stack(R) 
```

```
Traceback (most recent call last):

  File "<ipython-input-8-fd2533396aec>", line 2, in <module>
    R_, _, metadata = stp.io.import_mch_gif(fn)
```

AttributeError: module 'pysteps' has no attribute 'io'
While running this code I get an error stating pysteps has no module name io, while trying to load images using io.import_mch_gif(). There was though no error importing pysteps and I am running this on a directory which is not in pysteps folder.

**Comment by aperezhortal** [comment]
Hi @m-anand, I installed the latest pysteps's version on a clean environment but I'm not being able to reproduce the error. 

Can you provide us the output of the following commands:
```
import os
import pysteps as stp

print( os.getcwd() )
print( os.listdir() )
print( stp.__file__  )
print( dir(stp) )
```

**Comment by itsmohitanand** [comment]
> Hi @m-anand, I installed the latest pysteps's version on a clean environment but I'm not being able to reproduce the error.
> 
> Can you provide us the output of the following commands:
> 
> ```
> import os
> import pysteps as stp
> 
> print( os.getcwd() )
> print( os.listdir() )
> print( stp.__file__  )
> print( dir(stp) )
> ```

This is the result which I see

```
/Users/mohitanand/Documents/projects/predOF/examples
['run_deterministic_nowcast.py', 'cascade_decomposition.py', 'sample_mch_radar_composite_00.gif', 'sample_mch_radar_composite_01.gif', 'run_ensemble_nowcast.py', 'README.md', 'noise_generators.py', 'ensemble_verification.py', 'my_first_nowcast_with_pysteps.py']
None
['__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']
```
I copied the examples to other folder, it was initially inside the pysteps folder

**Comment by aperezhortal** [comment]
The **import pysteps as stp** statement is not working correctly. The imported package seems empty. 

Which is the ouput of: **print(stp.__path__)** ?

You can try uninstalling pysteps (*pip unsinstall pysteps*) and re-installing it again. Maybe there was an error in during the installation.

**Comment by itsmohitanand** [comment]
I uninstalled and installed it again and it works now. I believe I did something wrong for the first time. 
Thank you for the help.
