### ISSUE TITLE
PySTEPS using satellite data

### ISSUE THREAD

**Issue by wxguy** [pySTEPS/pysteps#420]
I have gone through the documentation and it appears that all examples are using radar days for nowcasting. I read some of the papers which days they used satellite data in PySTEPS.

Is it possible to that? Where can I refer to the documentation?

**Comment by dnerini** [comment]
Hi @wxguy, please have a look at #359 and #339: all nowcasting methods in pysteps can work with any type of variable, provided that it is formatted in the right way (essentially it needs to be on cartesian grid and passed as a numpy array). Of course, it needs also to be a suitable field for nowcasting, but this is left to the user to decide (I have successfully used pysteps on cloud cover and lightning observations, for example).

Hope this helps, feel free to reopen this issue if you need more help.

**Comment by wxguy** [comment]
Thank you for your response. 

I have gone through both the issues you have mentioned, but I don't think it gives any solution to the issue I intned to do.

May be, I am unable to put my question clearly. For the clarity, here is what I intend to do:-

1.  I have a sequence of 20 satellite datasets (IR1 is one of the variable which I intend to do nowcast) in **hdf** format.
2.  These datasets are saved in a local directory. 
3.  Open and extract `IR1` variable from each dataset (assume that it is in NumPy array in Cartesian grid format).
4.  Pass/ load it to pysteps (most/ all the examples shown in documentation are sample datasets only).
5.  Train the data with specific algorithm for the next few hours.
6.  Plot the data on a Geo Map.

**_How_** do I do the above? Is there any documentation specifically pointing to satellite dataset that are not included as sample datasets.

> I have successfully used pysteps on cloud cover and lightning observations, for example

Wow. That is what exactly (sort of) I am trying to do. Could you give some code example which I can try at my end. 

Again, just a suggestion. In the gallery section, maybe you can keep a programme to showcase how satellite datasets can be used for nowcasting. I am sure this would help beginners.
