### ISSUE TITLE
Import BOM reflectivity nc files, and converting from dBZ to rainrate or raindepth

### ISSUE THREAD

**Issue by jandye** [pySTEPS/pysteps#423]
Working on a project to compare radar data for two historical floods using the AURA historical ground reflectivity dataset.

Firstly, when trying to import BOM nc using the bom_rf3 importer, it only works where there is a "precipitation" key. However, the ground reflectivity uses a "reflectivity" key. Would it be best to create my own importer plugin? For now, I've just manually changed the importers.py in my python environment to add an additional elif statement to check for "reflectivity".

https://github.com/pySTEPS/pysteps/blob/917c83b28e17af9bff9e064df800f8e136bc0463/pysteps/io/importers.py#L459

``` python
    if "precipitation" in ds_rainfall.variables.keys():
        precipitation = ds_rainfall.variables["precipitation"][:]
    elif "reflectivity" in ds_rainfall.variables.keys():
        precipitation = ds_rainfall.variables["reflectivity"][:]
    else:
        precipitation = None
```

https://github.com/pySTEPS/pysteps/blob/917c83b28e17af9bff9e064df800f8e136bc0463/pysteps/io/importers.py#L540

``` python
    if "precipitation" in ds_rainfall.variables.keys():
        if "units" in ds_rainfall.variables["precipitation"].ncattrs():
            units = getattr(ds_rainfall.variables["precipitation"], "units")
            if units in ("kg m-2", "mm"):
                geodata["unit"] = "mm"
    elif "reflectivity" in ds_rainfall.variables.keys():
        if "units" in ds_rainfall.variables["reflectivity"].ncattrs():
            units = getattr(ds_rainfall.variables["reflectivity"], "units")
            if units in ("dBZ"):
                geodata["unit"] = "dBZ"
```

Also converting from dBZ to mm/hr should first be converted to linear units before applying the ZR function?

https://github.com/pySTEPS/pysteps/blob/917c83b28e17af9bff9e064df800f8e136bc0463/pysteps/utils/conversion.py#L96

``` python
        R = (10**(R/10) / zr_a) ** (1.0 / zr_b)
```

Or is this working as intended, and I should just convert dBZ to linear units first before passing to the conversion function? E.g.
``` python
R, metadata = conversion.to_rainrate(10**(R/10), metadata)
```

**Comment by dnerini** [comment]
Hi @jandye , I think it'd make sense to extend the existing BOM importer to reflectivity values. Perhaps @cvelascof can provide a quick feedback on this, but I think we would welcome a PR in that sense.

Concerning your question for the conversion from dBZ to rainrates, the transformation to linear units is already included in the method, see https://github.com/pySTEPS/pysteps/blob/917c83b28e17af9bff9e064df800f8e136bc0463/pysteps/utils/conversion.py#L57, so you don't need to do it (provided that the metadata `transform` is correctly set to `dB`). Does this answer your question?

**Comment by jandye** [comment]
Hi @dnerini, thanks for your help
