### ISSUE TITLE
Example scripts not working

### ISSUE THREAD

**Issue by aperezhortal** [pySTEPS/pysteps#43]
The following scripts are not working correctly after the changes in the extrapolation interfaces:

* __my_first_nowcast_with_pysteps.py__
* __run_deterministic_nowcast.py__
* __run_ensemble_nowcast.py__

They need to be updated to be compliant with the last updates in pysteps.

**Comment by itsmohitanand** [comment]
Is pysteps reference release 0.2 not in accordance with the latest pysteps distribution. I think that is the case. For my first_nowcast_with_pysteps.py I had to change the part #Perform the advection of the radar field. 

```
n_lead_times = 12 
extra_init = stp.extrapolation.semilagrangian.initialize(shape=R[1].shape)
R_fct = stp.extrapolation.semilagrangian.extrapolate(extrapolator=extra_init, R=R_[-1,:,:], V=UV, num_timesteps = n_lead_times)
```
I found it in the reference manual that there are only 3 arguments required (excluding optional) while I had to add the extrapolator as well, which I could only figure out after seeing the script. 
Secondly the extrapolator argument is nothing but related to the shape of my radar images. I still have no idea why it is required separately where theoretically it can be computed from R. 

P.S. I am new to the concepts of programming thus could be missing something very simple.

**Comment by aperezhortal** [comment]
Hi @m-anand, the library went through many modifications since the last release. There were important changes in the interfaces and functions and the examples were not updated. That is why this issue was created.

We are in the process of fixing the examples and update the documentation according to the new changes. 

With respect to your question about the **extrapolator**. This argument was implemented to improve performance in the nowcast functions. We are working in a simpler interface for the __pysteps.extrapolation__ modules.

**Comment by aperezhortal** [comment]
Solve by commits 1b2acf08c62d3e57147544bcd8441ad304281675 and 7d64b7127502186ed5df0113023181c3aed14c1e.
