### ISSUE TITLE
release 1.0.0

### ISSUE THREAD

**Issue by dnerini** [pySTEPS/pysteps#44]
We need to start working on the release that will be referenced in the publication we are preparing. 

There are in my opinion three main aspects that need to be addressed:

Name:
How should we name this release? Simply pysteps 0.3? Another option could be to name it pysteps 1.0. 
This would be in my opinion appropriate given that it will be the version described in the paper.

Priority changes yet to be included:
Are there important features that we need to focus on for the next release? Issues that we must solve?
Reorganizing SPROG in a separate method could be one example. 

Change log:
Start putting together all your main contributions since our last release 0.2.

**Comment by aperezhortal** [comment]
I agree with the V1.0 name. 

These issues should be resolved for this release are: #43 #45 
I [created a milestone](https://github.com/pySTEPS/pysteps/milestone/1) to keep track of the progess with these (and maybe others) issues.

**Comment by RubenImhoff** [comment]
Seeing the improvements and the efforts from all of you, v1.0 sounds like an appropriate choice for the model version!

**Comment by dnerini** [comment]
This change log should include all our main contributions to the V1.0.

- Change pysteps license from GPL to the less restrictive BSD-3
- Move documentation to Read the Docs ([https://pysteps.readthedocs.io/](https://pysteps.readthedocs.io/))
- Modify `setup.py` to explicitly link libraries in macOS
- Remove legacy config module
- Add [CONTRIBUTING.rst](https://github.com/pySTEPS/pysteps/blob/master/CONTRIBUTING.rst)
- Add test suites for interfaces and the io and verification modules
- Use Travis CI for testing
- Several docstring improvements
- Add exporter for KINEROS2 Rainfall files
- Add importer for MeteoSwiss AZC radar composites
- Add importer for KNMI HDF5 radar composites
- Add scripts for estimating velocity perturbator parameters
- Add modules for deriving the auto-correlation function (ACF) and estimating precipitation lifetime
- Implement a separate module `nowcasts.sprog` for S-PROG nowcasts
- Add new nowcasting module `nowcasts.sseps` that includes an experimental version of STEPS that allows for localization
- Implement interfaces for initializing and calling different FFT methods
- Rework of the extrapolation interface
- Faster implementation of the rank histogram with bug fixes
- Improve subplot handling in plot_precip_field
- Add method for plotting 1d Fourier spectra in log-log scale
- Add wrapper functions for easier computation of verification scores
- Rewrite the CRPS function to be compatible with the other probabilistic verification methods
- Add support for MaskedArray in `motion.dense_lucaskanade()`
- Improve masking in `nowcasts.steps` module

**Comment by loforest** [comment]
From my side there are some small additions/improvements:
- function for elegant plotting of 1d Fourier spectra in log-log scale
- utility function to remove rain/no-rain step before computing Fourier spectra
- option to use incremental mask also with S-PROG nowcast
- make 'mean' probability matching method independent from the type of mask used

**Comment by aperezhortal** [comment]
From me, only small improvements:

- Remove legacy config module
- Improve subplot handling in plot_precip_field.
- Add interface tests suite

**Comment by pulkkins** [comment]
Here is my changelog:

- Add scripts for estimating velocity perturbator parameters.
- Implement a separate module for S-PROG nowcasts.
- Implement interfaces for initializing and calling different FFT methods.
- Rework of the extrapolation interface (with @aperezhortal).
- Faster implementation of the rank histogram with bug fixes.
- Rewrite the CRPS function to be compatible with the other probabilistic verification methods.
- Several docstring improvements.

**Comment by loforest** [comment]
In addition there is:
- Function to derive the full theoretical auto-correlation function (ACF)
- New module to estimate precipitation lifetimes

**Comment by dnerini** [comment]
I think we have addressed all pending issues for V1.0. If I haven't forgot anything important, we should now be ready for the next release. 

I propose to release V1.0 together with the submission of the pysteps publication.

**Comment by dnerini** [comment]
Now v1.0.0 is available, well done to everyone!

**Comment by loforest** [comment]
Very well done guys!
Everyone deserves a break now :-)

Il Dom 7 Apr 2019, 22:22 Daniele Nerini <notifications@github.com> ha
scritto:
