### ISSUE TITLE
Slack sign-up page for PySteps

### ISSUE THREAD

**Issue by Tom-Hamill-weather** [pySTEPS/pysteps#444]
This link on the pysteps page to set up an account for slack login wasn't working: https://pysteps-slackin.herokuapp.com/

**Comment by dnerini** [comment]
hi @Tom-Hamill-weather, thanks for reporting! Indeed, we deprecated the slack channel some time ago and currently only support github issues. Unfortunately, it looks like the content in the https://pysteps.github.io/ is outdated, I'll see to fix it.

Edit: done in https://github.com/pySTEPS/pysteps.github.io/commit/11e5ecc4d149b5f602071449e69de2f1e9080e71
