### ISSUE TITLE
Upload package to pypi and create anaconda packages

### ISSUE THREAD

**Issue by aperezhortal** [pySTEPS/pysteps#49]
For the new release, we can upload the python package to the Python Package index (https://pypi.org/) so that version can be installed simply by `pip install pysteps`. 

Also, since the installation of the package has some issues in other platforms different than Linux, we can create the anaconda installers for each OS. In that way, we can configure the conda package to make use of the anaconda compilers and avoid cross-platform compatibility issues.

**Comment by dnerini** [comment]
Any update on this @aperezhortal? Anything that we need to do before uploading the package to pypi?

**Comment by aperezhortal** [comment]
We can create a **1.0.0-beta** tag to test that the `pip install pysteps` installation from the [Test Python Package index](https://test.pypi.org/)) works in all platforms. This beta tag will be superseded by the release **1.0.0**. 

Then we can add the PySteps to [Conda-Forge](https://conda-forge.org/). I'm (slowly) preparing a pull request to https://github.com/conda-forge/staged-recipes with the PySteps recipe.

**Comment by aperezhortal** [comment]
An update on this.

I followed the steps in our [developer reference for PyPI](https://github.com/pySTEPS/pysteps/blob/master/doc/source/developer_guide/pypi.rst) and uploaded a the pySTEPS package to the Test Python Package index ([here](https://test.pypi.org/project/pysteps/)) to test it. You can install that  package using:  `pip install --index-url https://test.pypi.org/simple/ pysteps`

Also I push a [draft of the conda recipe](https://github.com/aperezhortal/staged-recipes/tree/master/recipes/pysteps) to be used in conda-forge.

After we release V1.0.0, we can upload the package to the Python Package index and then submit a pull request to conda-forge with our recipe.

**Comment by dnerini** [comment]
@aperezhortal this looks really great!

pysteps 1.0.0 is now available, meaning that we could also proceed with this issue when you have some time to work on it. Let me know if we can help in any way!

**Comment by aperezhortal** [comment]
[pysteps 1.0.0 is now in PyPI](https://pypi.org/project/pysteps/) :+1: 
@dnerini or @pulkkins, you can create an account in PyPI so I can add you as maintainers for the package.

Next step, conda-forge! I forked the stagged-recipes repo to the pySTEPS account so we can work on it in the [pysteps_recipe branch](https://github.com/pySTEPS/staged-recipes/tree/pysteps_recipe). I'm following the [guidelines in the official documentation](http://conda-forge.org/docs/maintainer/adding_pkgs.html#creating-recipes) for this recipe.

[EDIT]: [PR submitted to conda-forge/stagged-recipes](https://github.com/conda-forge/staged-recipes/pull/8110) 
[EDIT 2]: All the PR test passed! @dnerini  and @pulkkins, I added both of you as maintainers, you need to post a comment in the PR confirming you are willing to do it in the PR.

**Comment by pulkkins** [comment]
I created an account in PyPI, so can you add me as maintainer?

**Comment by aperezhortal** [comment]
We can now proudly tell everyone that pysteps is available in conda-forge for all the platforms! :sunglasses:

Since conda-forge and the default channels are not 100% compatible, it can happend that a missmatch in the versions available on each channel results in errors when the install environment is mixing packages from multiple channels. [A solution for this is to use conda-forge as the priority channel](https://conda-forge.org/docs/user/tipsandtricks.html#using-multiple-channels).

The repository with the recipe is in the [conda-forge pysteps-feedstock](https://github.com/conda-forge/pysteps-feedstock). 

This close the issue :tada:

**Comment by dnerini** [comment]
This is brilliant, thanks for all the great work, @aperezhortal !

We should now update our documentation accordingly.
