### ISSUE TITLE
Lucas-Kanade Robustness

### ISSUE THREAD

**Issue by 5fcgdaeb** [pySTEPS/pysteps#50]
If there are is precipitation data on a map, the Lucas-Kanade method throws a `ValueError` with the following details:
```
File "/python3.5/site-packages/pysteps/motion/lucaskanade.py", line 245, in _ShiTomasi_features_to_track
    raise ValueError("Shi-Tomasi found no good feature to be tracked.")
ValueError: Shi-Tomasi found no good feature to be tracked.
```

It is understandable that a motion field cannot be computed on an empty map but I see that more as a regular case rather than an exception/error. Could the API be modified slightly to make sure that an error is not raised?

**Comment by dnerini** [comment]
Hi @5fcgdaeb , thanks for your suggestion!
I totally agree with you, the robustness of the method can be improved in case of empty fields.

Commit c15edcba98827fa39b02829a758b6b89a7972ccb is an attempt in that direction: now a zero motion field is returned when no motion is detected and a simple UserWarning is raised.

This issue however opens a broader discussion about what should be behavior of pysteps methods when empty precipitation fields are passed. 

I also wonder what happens with VET and DARTS in such cases, @aperezhortal @spulkkin ?
We should aim for consistent way of handling such situations. 

I would therefore leave this issue open for the moment, as there are still some important aspects to discuss.

**Comment by aperezhortal** [comment]
I run the following snippet to test the behavior with zero fields::

```python
import pysteps
IMAGE_SIZE = 256 

for method_name in ["lk", "vet", "darts"]:
    opt_flow = pysteps.motion.interface.get_method(method_name)

    if method_name == "darts":
        UV = opt_flow(numpy.zeros((10, IMAGE_SIZE, IMAGE_SIZE)), verbose=False)
    else:
        UV = opt_flow(numpy.zeros((3, IMAGE_SIZE, IMAGE_SIZE)), verbose=False)

    print(method_name, UV.min(), UV.max())
```
In all the cases, the motion field is 0 and no error are raised. But, only Lucas-Kanade raises a UserWarning.

For VET, since all the precipitation fields are Zero, displacing the fields does not change the value of the cost function used to find the displacements. In consequence, VET returns a field equal or similar to the initial guess (which is zero by default).   

For example, the output of the following snippet is UV=1 on every point. 
```python
opt_flow = pysteps.motion.interface.get_method("vet")

UV = opt_flow(numpy.zeros((3, IMAGE_SIZE, IMAGE_SIZE)), verbose=False,
              first_guess=numpy.ones((2, 2, 2)))
print("VET", UV.min(), UV.max())
```

**Comment by dnerini** [comment]
Thanks @aperezhortal! In this case, I will remove the UserWarning for Lucas-Kanade and assume that the expected behavior in case of zero fields is to return zero motion.

I guess this closes the issue.
