### ISSUE TITLE
linking pysteps under the GPL3 license

### ISSUE THREAD

**Issue by dnerini** [pySTEPS/pysteps#56]
It has been pointed out that there may be an issue regarding the GPL3 license under which  pysteps is currently published. This concerns whether or not a non-GPL software can legally link to a GPL library (as explained in this [Wikipedia page](https://en.wikipedia.org/wiki/GNU_General_Public_License#Linking_and_derived_works)):

> if one releases a GPL-licensed entity to the public, there is an issue regarding linking: namely, whether a proprietary program that uses a GPL library is in violation of the GPL. 

 In essence, this boils down at whether or not using pysteps can be considered or not as "derivative work", which GPL clearly requires to be put under the same GPL.

Apparently this is a controversial matter and different opinion exist. 

I would like to see if anyone has comments/opinions on the issue. Maybe somebody with more experience with open-source lincenses could give us some advise? Should we consider using a different license?

I personally would prefer not to limit the use of pysteps from within non-GPL softwares, but this is of course open to discussion.

**Comment by aperezhortal** [comment]
The [GPL](https://tldrlegal.com/license/gnu-general-public-license-v3-(gpl-3)) is restrictive in the sense that enforces the "open source" idea. That means that, if you use a GPL library in you need to make the source code available also. 

An alternative is the [GNU Lesser General Public License (LGPL)](https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-(lgpl-3)). With that license, applications that use the library don't have to be redistributed under LGPL. That means, you don't need to distribute the surce code if you are only using the library. You only need to do it if you distribute a derived work. 

Another license that I personally like is [BSD-3](https://tldrlegal.com/license/bsd-3-clause-license-(revised)). It allows  almost unlimited freedom as long as you include the pysteps copyright and a copy of the license when you distribute any derivative work. 
BSD-3 is similar to the [MIT license](https://tldrlegal.com/license/mit-license#summary), but BSD don't allow to use the name of the copyright holder nor the names of its contributors to endorse or promote products derived from this software without permission. 

We need to discuss how "permissive" we want the license to be, and then, choose the license accordingly. I personally prefer permissive licenses.

To serve as a reference, below a list of opensoure package and their respective licenses.
- [py-art](https://github.com/ARM-DOE/pyart/blob/master/LICENSE.txt): Looks like a BSD-3 license.
- [pandas](https://github.com/pandas-dev/pandas/blob/master/LICENSE): BSD-3
- [numpy](https://github.com/numpy/numpy/blob/master/LICENSE.txt): Looks like a BSD-3 license.
- [xarray](https://github.com/pydata/xarray/blob/master/LICENSE): [Apache License](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0))
- [BALTRAD](https://openradarscience.org/2018/05/baltrad/): (LGPL)
- [wradlib](https://github.com/wradlib/wradlib/blob/master/LICENSE.txt): MIT license.
- [PyRadarMet ](https://openradarscience.org/2017/09/pyradarmet/): GPL
- [WRF model](https://github.com/wrf-model/WRF): Public domain

**Comment by wcwoo** [comment]
Sorry that I said I would bring this up but didn't, as I was too busy over the past couple of weeks. Thanks @dnerini for taking the initiative.

From the perspective of a potential user, we can happily use it as long as it's not strictly GPL.

**Comment by dnerini** [comment]
No worries @wcwoo, I decided to open the issue myself as I think it is something important to be discussed here. Thank you for having mentioned this issue in the first place.

And thanks @aperezhortal for the exhaustive overview. From my side this is now pretty clear: if the aim of pysteps is to become a general library for nowcasting purposes and related applications, then GPL is too restrictive as it would limit its use in non-GPL softwares. 

This said, I wouldn't know whether we should go for LGPL, BSD or MIT, I guess this also becomes a matter or taste. We could also consider which license is most popular among potential users of pysteps, and this is already nicely illustrated in the list above.

**Comment by dnerini** [comment]
It looks like we are now converging towards the [BSD-3](https://tldrlegal.com/license/bsd-3-clause-license-(revised)) license.
I will leave this discussion open for the moment, in case somebody has something to add or comment about the topic. We plan to update the pysteps license with the next V1.0.0 release.

**Comment by pkars** [comment]
I have no objections to this license change.

In fact, I wholeheartedly agree with switching to BSD-3 license. That'll help out in avoiding licensing problems in the future, if (when) pysteps library is used in operational nowcasting systems.

**Comment by dnerini** [comment]
Commit 9522198b37bd27b8ba20ea0ed6e315aeb77997e9 closes this issue.
