### ISSUE TITLE
Speedup of boolean summation

### ISSUE THREAD

**Issue by meteoswiss-mdr** [pySTEPS/pysteps#6]
Dear pysteps Team
It looks like one can speed-up the skill score calculation by converting the booleans to floats before the summation (roughly a factor of 30...).
I hope this helps!

```
    H = sum(H_idx.astype(float)) # hits
    M = sum(H_idx.astype(float)) # misses
    F = sum(H_idx.astype(float)) # false alarms
    R = sum(H_idx.astype(float)) # correct rejections
```

https://github.com/pySTEPS/pysteps/blob/3d8fda83d95af76ad04b3030e0ee75d0e544ee0c/pysteps/verification/detcatscores.py#L40

**Comment by dnerini** [comment]
I'm not sure why, but I've tested it and it is actually much faster, well done!

**Comment by pulkkins** [comment]
I reopened this issue because it appears in many other places in the verification module (e.g. the reliability diagram).

**Comment by pulkkins** [comment]
All booleans in the verification module are now converted to ints before summation (int is safer than float because the results are always guaranteed to be integer).
