### ISSUE TITLE
_generate_path function cannot convert paths appropriately. Generalisation could be helpful

### ISSUE THREAD

**Issue by itsmohitanand** [pySTEPS/pysteps#72]
https://github.com/pySTEPS/pysteps/blob/fcf2bcd8094585a460d062eed35873211b248945/pysteps/io/archive.py#L100

Pysteps source file snap

```
"mch_rzc": {
            "root_path": "/Users/mohitanand/Documents/projects/masters_project/data",
            "path_fmt": "%Y/Meteo_Swiss_Images_%m",             
	    	"fn_pattern": "meteoswiss.radar.precip.%Y%m%d%H%M",
            "fn_ext": "gif",
            "importer": "mch_gif",
            "timestep": 5,
            "importer_kwargs": {
                "product": "RZC",
                "unit": "mm/h",
                "accutime": 5
            }
```

The code to read the files 

```
import pysteps as stp
from pysteps import rcparams
from datetime import datetime

ds = stp.rcparams["data_sources"]["mch_rzc"]
starttime = datetime(2016,1,1)
importer = stp.io.get_method(ds.importer, "importer")
input_files = stp.io.find_by_date(starttime, ds.root_path, ds.path_fmt,ds.fn_pattern, ds.fn_ext, ds.timestep, 0, 1)
R, _, metaradar = stp.io.read_timeseries(input_files, importer, **ds.importer_kwargs)

```

Error

```
path /Users/mohitanand/Documents/projects/masters_project/data/2016/Meteo_Swiss_Images_%m not found.
path /Users/mohitanand/Documents/projects/masters_project/data/2016/Meteo_Swiss_Images_%m not found.
```

%m not being converted to the month value

**Comment by dnerini** [comment]
Hi @melioristic thanks for this report. @spulkkin maybe you can have a look at this?

**Comment by aperezhortal** [comment]
It seems that line 101 is causing the issue. Only format strings that start with **%** are formated using strftime. Otherwise a the same format string is returned.

https://github.com/pySTEPS/pysteps/blob/fcf2bcd8094585a460d062eed35873211b248945/pysteps/io/archive.py#L100-L101

**Comment by pulkkins** [comment]
Exactly. Why don't we just remove the if clause?

**Comment by aperezhortal** [comment]
I'm working on it. I'll also add a few tests for that function.

**Comment by aperezhortal** [comment]
@melioristic, Pull Request #76 should fix this issue. Let us know if you are still having problems.
