### ISSUE TITLE
Basemap EOL

### ISSUE THREAD

**Issue by juhi24** [pySTEPS/pysteps#8]
Basemap will be replaced by Cartopy and ["All new software development should try to use Cartopy whenever possible"](https://matplotlib.org/basemap/users/intro.html#cartopy-new-management-and-eol-announcement). Pysteps currently uses Basemap. If there are no major barriers, pysteps should probably aim to switch to Cartopy to avoid using deprecated modules.

While not all Basemap features are yet implemented in Cartopy, I've been using it for over a year without major issues. Also for visualizing radar products.

**Comment by pulkkins** [comment]
Since commit 425f1c0, the user can choose between two backends: basemap and cartopy. Basemap will be removed in a future release.
