### ISSUE TITLE
Why use np.roll(g[:-1], j)  instead of padding zero in autoregression?

### ISSUE THREAD

**Issue by Fangyh09** [pySTEPS/pysteps#85]
For line 131 at
https://github.com/pySTEPS/pysteps/blob/4a14e00fa56d43686c977bfcbbeb9c3412bda0b3/pysteps/timeseries/autoregression.py#L128-L134

```
G.append(np.roll(g[:-1], j)) 
```
Why use np.roll instead of padding zero?

//Yule=Walker Equation: http://www2.econ.osaka-u.ac.jp/~tanizaki/class/2014/model_analysis1/08.pdf P109

**Comment by pulkkins** [comment]
The Yule-Walker equation could also be solved by padding with zeros. However, using np.roll allows a more compact representation of the equation.
