### ISSUE TITLE
A possible bug in D -= V_inc if D_prev is None

### ISSUE THREAD

**Issue by Fangyh09** [pySTEPS/pysteps#86]
If D_prev is None and t == 0,
D -= V_inc(Line 151) is not right, it should be D -= V_inc/n_iter
https://github.com/pySTEPS/pysteps/blob/dde2b1318e4e98d320a87cc8644ce270423916f4/pysteps/extrapolation/semilagrangian.py#L135-L155

**Comment by pulkkins** [comment]
The division is done at line 133. Note that when using the /= operator, any changes to the elements of V_inc are reflected back to the function where interpolate_motion is called from.

**Comment by Fangyh09** [comment]
If D_prev is None and t == 0, interpolate_motion is not called.

**Comment by Fangyh09** [comment]
I think  "D -= V_inc/3" is better.

**Comment by dnerini** [comment]
@spulkkin you have any more comments of this? 
is this something we need to address?

**Comment by pulkkins** [comment]
I did a partial rewrite of the semi-Lagrangian extrapolator. The above issues should now have been fixed.
