### ISSUE TITLE
Which flow is better?

### ISSUE THREAD

**Issue by Fangyh09** [pySTEPS/pysteps#87]
I found the procedure to compute optical flow is slow. And tried another way(neural network) to compute it.
Which one looks better and reasonable? LK method or the new method? The results are:
------------------------------This repo LK method------------------------------
Time=t0:
![o_v2](https://user-images.githubusercontent.com/9389269/58933459-e730ec80-8799-11e9-9eaa-72baec27c4e6.png)
Time=t1:
![o_v11111](https://user-images.githubusercontent.com/9389269/58933439-d2545900-8799-11e9-871b-4b7644f34a9f.png)

------------------------------new method------------------------------
Time=t0:
![n_v1](https://user-images.githubusercontent.com/9389269/58933460-e8fab000-8799-11e9-80f8-122ebd4b6354.png)
Time=t1:
![n_v2](https://user-images.githubusercontent.com/9389269/58933463-eac47380-8799-11e9-8b5e-e50f1489fa42.png)

**Comment by dnerini** [comment]
Hi @Fangyh09
Interesting contribution! One way to compare optical flow estimations consists in computing the forecast error for both methods and see which one provides the best skill. 
See for example Section 5.1 in the pysteps reference publication, here:
https://www.geosci-model-dev-discuss.net/gmd-2019-94/

Hope this helps.

Kind regards
Daniele

**Comment by Fangyh09** [comment]
@dnerini  Thanks, I found ROC metric in https://pysteps.readthedocs.io/en/latest/auto_examples/plot_ensemble_verification.html#sphx-glr-auto-examples-plot-ensemble-verification-py.

**Comment by dnerini** [comment]
For example, yes, although the scores in that tutorial are for ensemble (probabilistic) forecasts, while you will be looking at deterministic predictions. 
You can therefore try to use  [deterministic continuous](https://pysteps.readthedocs.io/en/latest/generated/pysteps.verification.detcontscores.det_cont_fct.html#pysteps.verification.detcontscores.det_cont_fct) error metrics such as the mean absolute error and correlation coefficient, or [categorical ](https://pysteps.readthedocs.io/en/latest/generated/pysteps.verification.detcatscores.det_cat_fct.html#pysteps.verification.detcatscores.det_cat_fct) scores such as the critical success index (CSI). Those are the most commonly used scores. 
Alternatively, you can try spatial scores, which aim at providing the forecast skill for a range of spatial scales. You can find an example in this [tutorial](https://pysteps.readthedocs.io/en/latest/auto_examples/plot_extrapolation_nowcast.html#sphx-glr-auto-examples-plot-extrapolation-nowcast-py).

Again, I recommend you to have a look at the pysteps paper, where we have compared three different optical flow techniques (Section 5.1).

**Comment by Fangyh09** [comment]
@dnerini Thanks.
