### ISSUE TITLE
Any script  to evaluate different methods?

### ISSUE THREAD

**Issue by Fangyh09** [pySTEPS/pysteps#90]
Hi,
I implemented different optical flow methods, and I want to compare the results.
Is there any script to evaluate the results?

**Comment by dnerini** [comment]
Hi @Fangyh09,
Apart from the references already included in [this previous answer](https://github.com/pySTEPS/pysteps/issues/87#issuecomment-498961852), you can also have a look at the scripts that were used for the pysteps reference publication, [here](https://github.com/pySTEPS/pysteps-publication).
In particular, you can find [here](https://github.com/pySTEPS/pysteps-publication/blob/415d0bb69e70fa072a06138778085ed829260894/optical_flow_experiments/us_composite_analysis/compute_optflow_comparison_us_darts.py#L191) the code that evaluates the forecast using the MAE and CSI scores. 
Hope this helps.
