### ISSUE TITLE
Why local autoregression AR(2) is not used?

### ISSUE THREAD

**Issue by Fangyh09** [pySTEPS/pysteps#93]
Hi, 
I implemented local autoregression AR(2), and found it was pretty good. 
However, in this repo, global autoregression is used. https://github.com/pySTEPS/pysteps/blob/4c4ecc02f4baa600153c8991941d17ebf09998b7/pysteps/nowcasts/sprog.py#L226 Why not consider using local autoregression?  Is it because too time-consuming?

## local auto regression (with kernel size 3x3)
![nofft_R0](https://user-images.githubusercontent.com/9389269/59584174-ee4be900-910f-11e9-8441-b38fde394614.png)

![nofft_R1](https://user-images.githubusercontent.com/9389269/59584185-f572f700-910f-11e9-93e3-5e91c08846c1.png)

![nofft_R2](https://user-images.githubusercontent.com/9389269/59584189-f6a42400-910f-11e9-979c-995f27347135.png)

Predicted image:
![nofft_R3](https://user-images.githubusercontent.com/9389269/59584192-f86de780-910f-11e9-9d1a-1ead115bc528.png)

## global auto regression
![nofft_R0](https://user-images.githubusercontent.com/9389269/59584362-61555f80-9110-11e9-81c6-a83bcbc2fff7.png)

![nofft_R1](https://user-images.githubusercontent.com/9389269/59584364-631f2300-9110-11e9-9069-599a12dbbd9b.png)

![nofft_R2](https://user-images.githubusercontent.com/9389269/59584367-64505000-9110-11e9-9203-b869fb3f45a9.png)

Predicted image:
![nofft_R3](https://user-images.githubusercontent.com/9389269/59584368-65817d00-9110-11e9-80bb-9b771c3b5fff.png)

**Comment by dnerini** [comment]
Hi @Fangyh09 

The localization of the model parameters such as the autoregressive coefficients is a very interesting topic that we have only recently started to explore, see for instance the localization experiment in the recently submitted [GMD publication](https://www.geosci-model-dev-discuss.net/gmd-2019-94/).

The first aim of pysteps, however, was to provide state-of-the-art tools in nowcasting which, currently, involve global parameters. 

As you mentioned, the increase in computing time and memory usage is certainly one challenge. However, there is also the issue of providing a robust estimation of the local parameters.

If this topic interest you, you are very welcome to provide your contribution to pysteps. For more information, please refer to our [contributors guidelines](https://pysteps.readthedocs.io/en/latest/developer_guide/contributors_guidelines.html). 

We are very happy to provide you with feedback on your developments and experiments. As you did above, visual assessment is certainly a good starting point. 
As next, you could try to investigate the benefits of your local AR approach by looking at the verification scores.

Hope this helps and thank you for your inputs!

Kind regards
Daniele
